package com.dd.newqazaqalphabet.seabis;

/**
 * Created by dds86 on 03-Nov-17.
 */

public class Converter {
    public String cyrillicToLatin(String OCRresult) {
        OCRresult = OCRresult
                .replace("А", "A")
                .replace("а", "a")
                .replace("Ә", "A'")
                .replace("ә", "a'")
                .replace("Б", "B")
                .replace("б", "b")
                .replace("В", "V")
                .replace("в", "v")
                .replace("Г", "G")
                .replace("г", "g")
                .replace("Ғ", "G'")
                .replace("ғ", "g'")
                .replace("Д", "D")
                .replace("д", "d")
                .replace("Е", "E")
                .replace("е", "e")
                .replace("Ё", "I'o")
                .replace("ё", "i'o")
                .replace("Ж", "J")
                .replace("ж", "j")
                .replace("З", "Z")
                .replace("з", "z")
                .replace("И", "I'")
                .replace("и", "i'")
                .replace("Й", "I'")
                .replace("й", "i'")
                .replace("К", "K")
                .replace("к", "k")
                .replace("Қ", "Q")
                .replace("қ", "q")
                .replace("Л", "L")
                .replace("л", "l")
                .replace("М", "M")
                .replace("м", "m")
                .replace("Н", "N")
                .replace("н", "n")
                .replace("Ң", "N'")
                .replace("ң", "n'")
                .replace("О", "O")
                .replace("о", "o")
                .replace("Ө", "O'")
                .replace("ө", "o'")
                .replace("П", "P")
                .replace("п", "p")
                .replace("Р", "R")
                .replace("р", "r")
                .replace("С", "S")
                .replace("с", "s")
                .replace("Т", "T")
                .replace("т", "t")
                .replace("У", "Y'")
                .replace("у", "y'")
                .replace("Ұ", "U")
                .replace("ұ", "u")
                .replace("Ү", "U'")
                .replace("ү", "u'")
                .replace("Ф", "F")
                .replace("ф", "f")
                .replace("Х", "H")
                .replace("х", "h")
                .replace("Һ", "H")
                .replace("һ", "h")
                .replace("Ц", "C")
                .replace("ц", "c")
                .replace("Ч", "C'")
                .replace("ч", "c'")
                .replace("Ш", "S'")
                .replace("ш", "s'")
                .replace("Щ", "S's'")
                .replace("щ", "S's'")
                .replace("Ъ", "")
                .replace("ъ", "")
                .replace("Ы", "Y")
                .replace("ы", "y")
                .replace("І", "I")
                .replace("і", "i")
                .replace("Ь", "")
                .replace("ь", "")
                .replace("Э", "E")
                .replace("э", "e")
                .replace("Ю", "I'y'")
                .replace("ю", "i'y'")
                .replace("Я", "I'a")
                .replace("я", "i'a");

        return OCRresult;
    }

    public String latinToCyrillic(String OCRresult) {
        OCRresult = OCRresult
                //сперва будут заменяться String, потом characters
                //из String сперва будут заменяться длинные String, потом короткие String
                .replaceAll("I'o", "Ё")
                .replaceAll("i'o", "ё")
                .replaceAll("S's'", "Щ")
                .replaceAll("S's'", "щ")
                .replaceAll("I'y'", "Ю")
                .replaceAll("i'y'", "ю")
                .replaceAll("I'a", "Я")
                .replaceAll("i'a", "я")

                //Короткие String будут заменяться после длинных String
                .replaceAll("N'", "Ң")
                .replaceAll("n'", "ң")
                .replaceAll("O'", "Ө")
                .replaceAll("o'", "ө")
                .replaceAll("Y'", "У")
                .replaceAll("y'", "у")
                .replaceAll("U'", "Ү")
                .replaceAll("u'", "ү")
                .replaceAll("C'", "Ч")
                .replaceAll("c'", "ч")
                .replaceAll("S'", "Ш")
                .replaceAll("s'", "ш")
                .replaceAll("A'", "Ә")
                .replaceAll("a'", "ә")
                .replaceAll("G'", "Ғ")
                .replaceAll("g'", "ғ")
                .replaceAll("I'", "И")
                .replaceAll("i'", "и")
                .replaceAll("I'", "Й")
                .replaceAll("i'", "й")

                //characters будут заменяться после длинных и коротких String
                .replace("A", "А")
                .replace("a", "а")
                .replace("B", "Б")
                .replace("b", "б")
                .replace("V", "В")
                .replace("v", "в")
                .replace("G", "Г")
                .replace("g", "г")
                .replace("D", "Д")
                .replace("d", "д")
                .replace("E", "Е")
                .replace("e", "е")
                .replace("J", "Ж")
                .replace("j", "ж")
                .replace("Z", "З")
                .replace("z", "з")
                .replace("K", "К")
                .replace("k", "к")
                .replace("Q", "Қ")
                .replace("q", "қ")
                .replace("L", "Л")
                .replace("l", "л")
                .replace("M", "М")
                .replace("m", "м")
                .replace("N", "Н")
                .replace("n", "н")
                .replace("O", "О")
                .replace("o", "о")
                .replace("P", "П")
                .replace("p", "п")
                .replace("R", "Р")
                .replace("r", "р")
                .replace("S", "С")
                .replace("s", "с")
                .replace("T", "Т")
                .replace("t", "т")
                .replace("U", "Ұ")
                .replace("u", "ұ")
                .replace("F", "Ф")
                .replace("f", "ф")
                .replace("H", "Х")
                .replace("h", "х")
                .replace("H", "Һ")
                .replace("h", "һ")
                .replace("C", "Ц")
                .replace("c", "ц")
                .replace("Y", "Ы")
                .replace("y", "ы")
                .replace("I", "І")
                .replace("i", "і")
                .replace("E", "Э")
                .replace("e", "э")

        ;

        return OCRresult;
    }
}
