package com.dd.newqazaqalphabet.seabis;

/**
 * Created by dds86 on 03-Nov-17.
 */

public class Converter {
    public String cyrillicToLatin(String OCRresult) {
        OCRresult = OCRresult
                .replace("А", "A")
                .replace("а", "a")
                .replace("Ә", "A'")
                .replace("ә", "a'")
                .replace("Б", "B")
                .replace("б", "b")
                .replace("В", "V")
                .replace("в", "v")
                .replace("Г", "G")
                .replace("г", "g")
                .replace("Ғ", "G'")
                .replace("ғ", "g'")
                .replace("Д", "D")
                .replace("д", "d")
                .replace("Е", "E")
                .replace("е", "e")
                .replace("Ё", "I'o")
                .replace("ё", "i'o")
                .replace("Ж", "J")
                .replace("ж", "j")
                .replace("З", "Z")
                .replace("з", "z")
                .replace("И", "I'")
                .replace("и", "i'")
                .replace("Й", "I'")
                .replace("й", "i'")
                .replace("К", "K")
                .replace("к", "k")
                .replace("Қ", "Q")
                .replace("қ", "q")
                .replace("Л", "L")
                .replace("л", "l")
                .replace("М", "M")
                .replace("м", "m")
                .replace("Н", "N")
                .replace("н", "n")
                .replace("Ң", "N'")
                .replace("ң", "n'")
                .replace("О", "O")
                .replace("о", "o")
                .replace("Ө", "O'")
                .replace("ө", "o'")
                .replace("П", "P")
                .replace("п", "p")
                .replace("Р", "R")
                .replace("р", "r")
                .replace("С", "S")
                .replace("с", "s")
                .replace("Т", "T")
                .replace("т", "t")
                .replace("У", "Y'")
                .replace("у", "y'")
                .replace("Ұ", "U")
                .replace("ұ", "u")
                .replace("Ү", "U'")
                .replace("ү", "u'")
                .replace("Ф", "F")
                .replace("ф", "f")
                .replace("Х", "H")
                .replace("х", "h")
                .replace("Һ", "H")
                .replace("һ", "h")
                .replace("Ц", "C")
                .replace("ц", "c")
                .replace("Ч", "C'")
                .replace("ч", "c'")
                .replace("Ш", "S'")
                .replace("ш", "s'")
                .replace("Щ", "S's'")
                .replace("щ", "S's'")
                .replace("Ъ", "")
                .replace("ъ", "")
                .replace("Ы", "Y")
                .replace("ы", "y")
                .replace("І", "I")
                .replace("і", "i")
                .replace("Ь", "")
                .replace("ь", "")
                .replace("Э", "E")
                .replace("э", "e")
                .replace("Ю", "I'y'")
                .replace("ю", "i'y'")
                .replace("Я", "I'a")
                .replace("я", "i'a")
        ;

        return OCRresult;
    }

    public String cyrillicToSaebiz(String OCRresult) {
        OCRresult = OCRresult
                .replace("А", "A")
                .replace("а", "a")
                .replace("Ә", "Ae")
                .replace("ә", "ae")
                .replace("Б", "B")
                .replace("б", "b")
                .replace("В", "V")
                .replace("в", "v")
                .replace("Г", "G")
                .replace("г", "g")
                .replace("Ғ", "Gh")
                .replace("ғ", "gh")
                .replace("Д", "D")
                .replace("д", "d")
                .replace("Е", "E")
                .replace("е", "e")
                .replace("Ё", "E")
                .replace("ё", "e")
                .replace("Ж", "Zh")
                .replace("ж", "zh")
                .replace("З", "Z")
                .replace("з", "z")
                .replace("И", "I")
                .replace("и", "i")
                .replace("Й", "J")
                .replace("й", "j")
                .replace("К", "K")
                .replace("к", "k")
                .replace("Қ", "Q")
                .replace("қ", "q")
                .replace("Л", "L")
                .replace("л", "l")
                .replace("М", "M")
                .replace("м", "m")
                .replace("Н", "N")
                .replace("н", "n")
                .replace("Ң", "Ng")
                .replace("ң", "ng")
                .replace("О", "O")
                .replace("о", "o")
                .replace("Ө", "Oe")
                .replace("ө", "oe")
                .replace("П", "P")
                .replace("п", "p")
                .replace("Р", "R")
                .replace("р", "r")
                .replace("С", "S")
                .replace("с", "s")
                .replace("Т", "T")
                .replace("т", "t")
                .replace("У", "W")
                .replace("у", "w")
                .replace("Ұ", "U")
                .replace("ұ", "u")
                .replace("Ү", "Ue")
                .replace("ү", "ue")
                .replace("Ф", "F")
                .replace("ф", "f")
                .replace("Х", "H")
                .replace("х", "h")
                .replace("Һ", "H")
                .replace("һ", "h")
                .replace("Ц", "C")
                .replace("ц", "c")
                .replace("Ч", "Ch")
                .replace("ч", "ch")
                .replace("Ш", "Sh")
                .replace("ш", "sh")
                .replace("Щ", "Sh")
                .replace("щ", "sh")
                .replace("Ъ", "")
                .replace("ъ", "")
                .replace("Ы", "Y")
                .replace("ы", "y")
                .replace("І", "I")
                .replace("і", "i")
                .replace("Ь", "")
                .replace("ь", "")
                .replace("Э", "E")
                .replace("э", "e")
                .replace("Ю", "Iy")
                .replace("ю", "iy")
                .replace("Я", "Ia")
                .replace("я", "ia")

        ;

        return OCRresult;
    }

    public String cyrillicToAcute(String OCRresult) {
        OCRresult = OCRresult
                .replace("А", "A")
                .replace("а", "a")
                .replace("Ә", "Á")
                .replace("ә", "á")
                .replace("Б", "B")
                .replace("б", "b")
                .replace("В", "V")
                .replace("в", "v")
                .replace("Г", "G")
                .replace("г", "g")
                .replace("Ғ", "Ǵ")
                .replace("ғ", "ǵ")
                .replace("Д", "D")
                .replace("д", "d")
                .replace("Е", "E")
                .replace("е", "e")
                .replace("Ё", "É")
                .replace("ё", "é")
                .replace("Ж", "J")
                .replace("ж", "j")
                .replace("З", "Z")
                .replace("з", "z")
                .replace("И", "Í")
                .replace("и", "í")
                .replace("Й", "Í")
                .replace("й", "í")
                .replace("К", "K")
                .replace("к", "k")
                .replace("Қ", "Ḱ")
                .replace("қ", "ḱ")
                .replace("Л", "L")
                .replace("л", "l")
                .replace("М", "M")
                .replace("м", "m")
                .replace("Н", "N")
                .replace("н", "n")
                .replace("Ң", "Ń")
                .replace("ң", "ń")
                .replace("О", "O")
                .replace("о", "o")
                .replace("Ө", "Ó")
                .replace("ө", "ó")
                .replace("П", "P")
                .replace("п", "p")
                .replace("Р", "R")
                .replace("р", "r")
                .replace("С", "S")
                .replace("с", "s")
                .replace("Т", "T")
                .replace("т", "t")
                .replace("У", "Ý")
                .replace("у", "ý")
                .replace("Ұ", "U")
                .replace("ұ", "u")
                .replace("Ү", "Ú")
                .replace("ү", "ú")
                .replace("Ф", "F")
                .replace("ф", "f")
                .replace("Х", "H")
                .replace("х", "h")
                .replace("Һ", "H")
                .replace("һ", "h")
                .replace("Ц", "C")
                .replace("ц", "c")
                .replace("Ч", "Ć")
                .replace("ч", "ć")
                .replace("Ш", "Ś")
                .replace("ш", "ś")
                .replace("Щ", "Ś")
                .replace("щ", "ś")
                .replace("Ъ", "")
                .replace("ъ", "")
                .replace("Ы", "Y")
                .replace("ы", "y")
                .replace("І", "I")
                .replace("і", "i")
                .replace("Ь", "")
                .replace("ь", "")
                .replace("Э", "E")
                .replace("э", "e")
                .replace("Ю", "Íý")
                .replace("ю", "íý")
                .replace("Я", "Íа")
                .replace("я", "íа")


        ;

        return OCRresult;
    }

    public String latinToCyrillic(String OCRresult) {
        OCRresult = OCRresult
                //сперва будут заменяться String, потом characters
                //из String сперва будут заменяться длинные String, потом короткие String
                .replaceAll("I'o","Ё")
                .replaceAll("i'o","ё")
                .replaceAll("S's'","Щ")
                .replaceAll("S's'","щ")
                .replaceAll("I'y'","Ю")
                .replaceAll("i'y'","ю")
                .replaceAll("I'a","Я")
                .replaceAll("i'a","я")


                //Короткие String будут заменяться после длинных String
                .replaceAll("N'","Ң")
                .replaceAll("n'","ң")
                .replaceAll("O'","Ө")
                .replaceAll("o'","ө")
                .replaceAll("Y'","У")
                .replaceAll("y'","у")
                .replaceAll("U'","Ү")
                .replaceAll("u'","ү")
                .replaceAll("C'","Ч")
                .replaceAll("c'","ч")
                .replaceAll("S'","Ш")
                .replaceAll("s'","ш")
                .replaceAll("A'","Ә")
                .replaceAll("a'","ә")
                .replaceAll("G'","Ғ")
                .replaceAll("g'","ғ")
                .replaceAll("I'","И")
                .replaceAll("i'","и")
                .replaceAll("I'","Й")
                .replaceAll("i'","й")


                //characters будут заменяться после длинных и коротких String
                .replace("A","А")
                .replace("a","а")
                .replace("B","Б")
                .replace("b","б")
                .replace("V","В")
                .replace("v","в")
                .replace("G","Г")
                .replace("g","г")
                .replace("D","Д")
                .replace("d","д")
                .replace("E","Е")
                .replace("e","е")
                .replace("J","Ж")
                .replace("j","ж")
                .replace("Z","З")
                .replace("z","з")
                .replace("K","К")
                .replace("k","к")
                .replace("Q","Қ")
                .replace("q","қ")
                .replace("L","Л")
                .replace("l","л")
                .replace("M","М")
                .replace("m","м")
                .replace("N","Н")
                .replace("n","н")
                .replace("O","О")
                .replace("o","о")
                .replace("P","П")
                .replace("p","п")
                .replace("R","Р")
                .replace("r","р")
                .replace("S","С")
                .replace("s","с")
                .replace("T","Т")
                .replace("t","т")
                .replace("U","Ұ")
                .replace("u","ұ")
                .replace("F","Ф")
                .replace("f","ф")
                .replace("H","Х")
                .replace("h","х")
                .replace("H","Һ")
                .replace("h","һ")
                .replace("C","Ц")
                .replace("c","ц")
                .replace("Y","Ы")
                .replace("y","ы")
                .replace("I","І")
                .replace("i","і")
                .replace("E","Э")
                .replace("e","э")



        ;

        return OCRresult;
    }

    public String latinToAcute(String OCRresult) {
        OCRresult = OCRresult
                //сперва будут заменяться String, потом characters
                //из String сперва будут заменяться длинные String, потом короткие String
                .replaceAll("I'o", "È")
                .replaceAll("i'o", "è")
                .replaceAll("S's'", "Ś")
                .replaceAll("S's'", "ś")
                .replaceAll("I'y'", "Íý")
                .replaceAll("i'y'", "íý")
                .replaceAll("I'a", "Íа")
                .replaceAll("i'a", "íа")


                //Короткие String будут заменяться после длинных String
                .replaceAll("N'", "Ń")
                .replaceAll("n'", "ń")
                .replaceAll("O'", "Ó")
                .replaceAll("o'", "ó")
                .replaceAll("Y'", "Ý")
                .replaceAll("y'", "ý")
                .replaceAll("U'", "Ú")
                .replaceAll("u'", "ú")
                .replaceAll("C'", "Ć")
                .replaceAll("c'", "ć")
                .replaceAll("S'", "Ś")
                .replaceAll("s'", "ś")
                .replaceAll("A'", "À")
                .replaceAll("a'", "à")
                .replaceAll("G'", "Ǵ")
                .replaceAll("g'", "ǵ")
                .replaceAll("I'", "Í")
                .replaceAll("i'", "í")
                .replaceAll("I'", "Í")
                .replaceAll("i'", "í")


                //characters будут заменяться после длинных и коротких String
                .replace("A", "A")
                .replace("a", "a")
                .replace("B", "B")
                .replace("b", "b")
                .replace("V", "V")
                .replace("v", "v")
                .replace("G", "G")
                .replace("g", "g")
                .replace("D", "D")
                .replace("d", "d")
                .replace("E", "E")
                .replace("e", "e")
                .replace("J", "J")
                .replace("j", "j")
                .replace("Z", "Z")
                .replace("z", "z")
                .replace("K", "K")
                .replace("k", "k")
                .replace("Q", "Ḱ")
                .replace("q", "ḱ")
                .replace("L", "L")
                .replace("l", "l")
                .replace("M", "M")
                .replace("m", "m")
                .replace("N", "N")
                .replace("n", "n")
                .replace("O", "O")
                .replace("o", "o")
                .replace("P", "P")
                .replace("p", "p")
                .replace("R", "R")
                .replace("r", "r")
                .replace("S", "S")
                .replace("s", "s")
                .replace("T", "T")
                .replace("t", "t")
                .replace("U", "U")
                .replace("u", "u")
                .replace("F", "F")
                .replace("f", "f")
                .replace("H", "H")
                .replace("h", "h")
                .replace("H", "H")
                .replace("h", "h")
                .replace("C", "C")
                .replace("c", "c")
                .replace("Y", "Y")
                .replace("y", "y")
                .replace("I", "I")
                .replace("i", "i")
                .replace("E", "E")
                .replace("e", "e")


        ;

        return OCRresult;
    }

    public String latinToSaebiz(String OCRresult) {
        OCRresult = OCRresult
                //сперва будут заменяться String, потом characters
                //из String сперва будут заменяться длинные String, потом короткие String
                .replaceAll("I'o", "E")
                .replaceAll("i'o", "e")
                .replaceAll("S's'", "Sh")
                .replaceAll("S's'", "sh")
                .replaceAll("I'y'", "Iy")
                .replaceAll("i'y'", "iy")
                .replaceAll("I'a", "Ia")
                .replaceAll("i'a", "ia")


                //Короткие String будут заменяться после длинных String
                .replaceAll("N'", "Ng")
                .replaceAll("n'", "ng")
                .replaceAll("O'", "Oe")
                .replaceAll("o'", "oe")
                .replaceAll("Y'", "W")
                .replaceAll("y'", "w")
                .replaceAll("U'", "Ue")
                .replaceAll("u'", "ue")
                .replaceAll("C'", "Ch")
                .replaceAll("c'", "ch")
                .replaceAll("S'", "Sh")
                .replaceAll("s'", "sh")
                .replaceAll("A'", "Ae")
                .replaceAll("a'", "ae")
                .replaceAll("G'", "Gh")
                .replaceAll("g'", "gh")
                .replaceAll("I'", "I")
                .replaceAll("i'", "i")
                .replaceAll("I'", "J")
                .replaceAll("i'", "j")


                //characters будут заменяться после длинных и коротких String
                .replace("A", "A")
                .replace("a", "a")
                .replace("B", "B")
                .replace("b", "b")
                .replace("V", "V")
                .replace("v", "v")
                .replace("G", "G")
                .replace("g", "g")
                .replace("D", "D")
                .replace("d", "d")
                .replace("E", "E")
                .replace("e", "e")
                .replace("J", "Zh")
                .replace("j", "zh")
                .replace("Z", "Z")
                .replace("z", "z")
                .replace("K", "K")
                .replace("k", "k")
                .replace("Q", "Q")
                .replace("q", "q")
                .replace("L", "L")
                .replace("l", "l")
                .replace("M", "M")
                .replace("m", "m")
                .replace("N", "N")
                .replace("n", "n")
                .replace("O", "O")
                .replace("o", "o")
                .replace("P", "P")
                .replace("p", "p")
                .replace("R", "R")
                .replace("r", "r")
                .replace("S", "S")
                .replace("s", "s")
                .replace("T", "T")
                .replace("t", "t")
                .replace("U", "U")
                .replace("u", "u")
                .replace("F", "F")
                .replace("f", "f")
                .replace("H", "H")
                .replace("h", "h")
                .replace("H", "H")
                .replace("h", "h")
                .replace("C", "C")
                .replace("c", "c")
                .replace("Y", "Y")
                .replace("y", "y")
                .replace("I", "I")
                .replace("i", "i")
                .replace("E", "E")
                .replace("e", "e")


        ;
        return OCRresult;
    }


}
